### ISSUE TITLE
Expandables have lost their internal bottom spacing

### ISSUE THREAD

**Issue by Scotchester** [cfpb/capital-framework#462] opened 2017-03-23 19:45 UTC
Our `:last-child { margin-bottom: 0; }` [rule](https://github.com/cfpb/capital-framework/blob/canary/src/cf-core/src/cf-base.less#L369-L371) has eliminated the bottom spacing in all expandables, which were counting on their last child's bottom margin to be there.

## Current behavior

Expandables have no spacing at the bottom of their content area.

## Expected behavior

Expandables have 15px spacing at the bottom of their content area.

## Steps to replicate behavior

1. [Pull the cf-v4 branch of design-manual](https://github.com/cfpb/design-manual/pull/466) and run it locally
2. View the Expandables page

## Screenshots

__Current__

<img width="580" alt="screen shot 2017-03-23 at 15 22 44" src="https://cloud.githubusercontent.com/assets/1044670/24266714/35dc45e0-0fde-11e7-9add-a8adb388f558.png">

__Expected__

<img width="574" alt="screen shot 2017-03-23 at 15 40 50" src="https://cloud.githubusercontent.com/assets/1044670/24267082/7449a3b2-0fdf-11e7-9bb1-395819c88ba4.png">

**Comment by jimmynotjim** [comment] 2017-03-30 14:47
@Scotchester this is a duplicate of #234

**Comment by Scotchester** [comment] 2017-03-30 15:57
No, it's not. It's affecting _all_ expandables, and the cause is different than the one identified in that issue, and its preceding issue, cfpb/cfgov-refresh#487.

**Closed** 2017-04-24 21:05 UTC
